/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file_op.h"

bool_t
xdr_file_result (XDR *xdrs, file_result *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->data, ~0))
		 return FALSE;
	return TRUE;
}
