/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_OP_H_RPCGEN
#define _FILE_OP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct file_result {
	char *data;
};
typedef struct file_result file_result;

#define PRINTER 0x2fffffff
#define PRINTER_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define READ_FILE 1
extern  file_result * read_file_1(char **, CLIENT *);
extern  file_result * read_file_1_svc(char **, struct svc_req *);
#define DELETE_FILE 2
extern  file_result * delete_file_1(char **, CLIENT *);
extern  file_result * delete_file_1_svc(char **, struct svc_req *);
extern int printer_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READ_FILE 1
extern  file_result * read_file_1();
extern  file_result * read_file_1_svc();
#define DELETE_FILE 2
extern  file_result * delete_file_1();
extern  file_result * delete_file_1_svc();
extern int printer_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file_result (XDR *, file_result*);

#else /* K&R C */
extern bool_t xdr_file_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_OP_H_RPCGEN */
